// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLFkhk9k_-AEy4zHl6-A2JfJWxDxArkM',
    appId: '1:149514599204:web:a34badcc82623bcfcc91b1',
    messagingSenderId: '149514599204',
    projectId: 'todolist-app-fad3a',
    authDomain: 'todolist-app-fad3a.firebaseapp.com',
    storageBucket: 'todolist-app-fad3a.appspot.com',
    measurementId: 'G-TQ8T3SJLS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhHv2ylllx_goiMNl3VWoLYDdMKdCn4sc',
    appId: '1:149514599204:android:79c2696c9ac52841cc91b1',
    messagingSenderId: '149514599204',
    projectId: 'todolist-app-fad3a',
    storageBucket: 'todolist-app-fad3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPqo0USmsLHYee6byBYv3OckO1GuT4qis',
    appId: '1:149514599204:ios:ca5ba6de768e6740cc91b1',
    messagingSenderId: '149514599204',
    projectId: 'todolist-app-fad3a',
    storageBucket: 'todolist-app-fad3a.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPqo0USmsLHYee6byBYv3OckO1GuT4qis',
    appId: '1:149514599204:ios:ca5ba6de768e6740cc91b1',
    messagingSenderId: '149514599204',
    projectId: 'todolist-app-fad3a',
    storageBucket: 'todolist-app-fad3a.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlLFkhk9k_-AEy4zHl6-A2JfJWxDxArkM',
    appId: '1:149514599204:web:a1df4be409cbf849cc91b1',
    messagingSenderId: '149514599204',
    projectId: 'todolist-app-fad3a',
    authDomain: 'todolist-app-fad3a.firebaseapp.com',
    storageBucket: 'todolist-app-fad3a.appspot.com',
    measurementId: 'G-G9BLBSREVP',
  );
}
